### ISSUE TITLE
Set seed for reproducible resampling results

### ISSUE THREAD

**Issue by katherinesmith** [Illumina/ExpansionHunterDenovo#3]
Currently the results of outlier analysis can vary from run to run for both the locus and motif based analysis. More specifically, top_case_zscore can vary and this sometimes leads to different numbers of lines being written to the output .tsv.

I believe that this is due to the use of numpy [random.choice()](https://github.com/Illumina/ExpansionHunterDenovo/blob/e7fa0e027e8cdd6d07528d97b33a721ecb1b2703/scripts/core/common.py#L155) without setting numpy random.seed(). It would be great to set a seed so that results can be reproduced exactly.

**Comment by egor-dolzhenko** [comment]
Thank you for noticing and reporting the problem. We will fix this shortly.

**Comment by egor-dolzhenko** [comment]
I am sorry this took awhile! The [v0.8.1 release](https://github.com/Illumina/ExpansionHunterDenovo/releases/tag/v0.8.1) should fix the issue.

**Comment by katherinesmith** [comment]
Thank you @egor-dolzhenko! Classic choice of seed :)
