### ISSUE TITLE
Non PCR-free WGS

### ISSUE THREAD

**Issue by wengkhong** [Illumina/ExpansionHunterDenovo#31]
Hi. I was wondering if ExpansionHunterDenovo has been tested on non PCR-free WGS samples?

**Comment by egor-dolzhenko** [comment]
Thanks for the question! The program should work on non PCR-free WGS samples, but there will be limits on what kind of expansions it would be able to detect. For example, very long 100% GC repeats might not amplify in PCR+ data well and so expansions of such repeats would be hard to detect.

Did I answer your question? Please let me know if something is not clear.

**Comment by wengkhong** [comment]
Hi Egor. Thanks for the reply. Am looking for GGC repeats, so you're probably right in that they'll be hard to detect. Will give it a try anyway. We have +ve cases identified in Nanopore with matching Truseq Nano data. Will see how those samples look.

**Comment by egor-dolzhenko** [comment]
This sounds good! It might be helpful to visualize read pileup in the region that is expected to harbor the expansion in IGV to check for read dropout or any other coverage anomalies. If I can assist with interpreting the pileup or the output of the program, please feel free to reach out anytime (edolzhenko@illumina.com).
