### ISSUE TITLE
Could you please tell me how to filter the result with the zscore?

### ISSUE THREAD

**Issue by swlx08** [Illumina/ExpansionHunterDenovo#38]
Dear professor,
Thank you very much for this amazing software. I am working on my WGS data to identify the rare TR expansions with EHdn. After running outlier analysis and ANNOVAR annotation I got 42947 TR repeats as shown in the table below:

![图片](https://user-images.githubusercontent.com/36035647/124412779-db9dbe80-dd81-11eb-9ef8-798135430c40.png)

Could you please tell me how could I filter the results based on the "top_case_zscore"? Is there any suggested threshold for this value? Thank you very much in advance.

By the way, could you please show me whether EHdn can deal with cram files or not? I asked this because I want to download the data of 1000 genomes, which are all in cram format. But in the Github page of EHdn, I did not see any description about cram files.

Best regards,
Stanley
---------
Guangzhou Institute of Pediatrics
Guangzhou Women and Children's Medical Center
9 Jinsui Road, Guangzhou, Guangdong, 510623, P.R.China
Office: +86-20-38857702

**Comment by egor-dolzhenko** [comment]
Hello Stanley,

Thank you for using EHdn. We had good results with using a Z-score threshold of 10 (see this [document for more details](https://github.com/Illumina/ExpansionHunterDenovo/blob/master/documentation/09_Repeat_prioritization_strategies.md)).  

And yes, EHdn will work with cram files. Thanks for catching this omission -- we will improve the documentation.

I hope this helps. Please let me know if you have any other questions.

Best wishes,
Egor

**Comment by swlx08** [comment]
> 


> 
> Hello Stanley,
> 
> Thank you for using EHdn. We had good results with using a Z-score threshold of 10 (see this [document for more details](https://github.com/Illumina/ExpansionHunterDenovo/blob/master/documentation/09_Repeat_prioritization_strategies.md)).
> 
> And yes, EHdn will work with cram files. Thanks for catching this omission -- we will improve the documentation.
> 
> I hope this helps. Please let me know if you have any other questions.
> 
> Best wishes,
> Egor

Dear Egor,

**Comment by egor-dolzhenko** [comment]
Happy to help!
