### ISSUE TITLE
manifest for outlier

### ISSUE THREAD

**Issue by hchetia** [Illumina/ExpansionHunterDenovo#41]
Does manifest for outlier analysis have to be different than the one for case control analysis?

**Comment by egor-dolzhenko** [comment]
The manifest file is the same. Were there any issues with running the outlier analysis?

**Comment by hchetia** [comment]
Hi @egor-dolzhenko 
Yes, running outlier analysis for motif and locus both gives me empty output tsv files.
However, while the program is running, I get the prompts just like for successful runs.
![image](https://user-images.githubusercontent.com/64626735/127098554-4b680641-1afb-491c-a63e-fa66ce583812.png)

I am not sure why it isn't working.

**Comment by egor-dolzhenko** [comment]
Hi @hchetia. It looks like EHdn may not be detecting any outliers. How many cases and how many controls do you have in your dataset?

**Comment by hchetia** [comment]
Hi Egor,
I am using one case and one control. I also tried running both as cases.
When I used 2 case and 2 controls, I did get results though. Is that the reason?

**Comment by egor-dolzhenko** [comment]
Yes, that's right. EHdn works best with relatively large groups of controls (50+). @mfbennett may be able to share EHdn profiles for some controls if you don't already have an appropriate collection of control samples.

**Comment by hchetia** [comment]
Hi @egor-dolzhenko @mfbennett that would be immensely helpful.

**Comment by mfbennett** [comment]
Hi @hchetia I'd be happy to share EHdn STR profiles for some controls, please feel free to email me at mark.bennett@wehi.edu.au

**Comment by hchetia** [comment]
Hi Mark,
I sent an email yesterday. 
best,
Hasna

**Comment by hchetia** [comment]
I will close this issue and wait for @mfbennett 's email!
Thanks to both of you.
