### ISSUE TITLE
More questions about EHdn

### ISSUE THREAD

**Issue by swlx08** [Illumina/ExpansionHunterDenovo#42]
Dear Egor,

Sorry to interrupt you again. I still hope to ask for four more questions about EHdn.

1. The table shown below is the result for outlier locus analysis. I noticed that some counts in "high_case_counts", like 2.26 in NT311 (indicated by red line), was less than the counts in the "Counts" column, like 12.18, 12.66 and 19.11. So does it means that some control samples have longer TR expansions （12.18, 12.66 and 19.11） than those of the case samples （2.26, 4.06 and 2.97）?

![图片](https://user-images.githubusercontent.com/36035647/126931067-ceccfbc1-7c79-47c7-8bc5-66ffef2509ba.png)

2. The "counts" in outlier locus analysis means "Nonzero counts for all samples". So for the first row of the table, this TR expansion was only detected in 13 samples (4.06, 7.59, 22.46, 1.10, 2.26, 12.18, 2.97, 1.13, 8.30, 4.83, 12.66, 19.11 and 9.09), right? Could I get the case/control ID (like NT311) of these counts?

3. Could EHdn distinguish between homozygous mutations and heterozygous mutations?

4. Whether the TR expansions detected are spontaneous mutation (or dominant mutation) or not?

Best regards,
Stanley

**Comment by egor-dolzhenko** [comment]
Hi Stanley. Thank you for the questions.

1. That's right. The vast majority of controls have very low counts (zero) but a few controls have very high counts.
2. That's right, long repeats were detected only in 13 samples. You could get the raw counts from the corresponding [multisample profile](https://github.com/Illumina/ExpansionHunterDenovo/blob/master/documentation/06_Merging_profiles.md). We will add an option to display sample names for all counts in the "counts" column in the future.
3. Unfortunately not yet. However, long homozygous expansions will generate higher counts (of anchored in-repeat reads) compared to long heterozygous expansions.
4. Could you please explain this question a bit more? I am not sure I understood it.

I hope this helps! Please let me know if any of my answers are not clear.

Best wishes,
Egor

**Comment by swlx08** [comment]
Dear Egor,

Thank you very much for your answer. Sorry I hope to ask more questions.
For question 1, since a few controls have very high counts (like 19.11), could I say this TR expansion is less pathogenic (highest case count: 22.46) when compared to other TRs?

And by the way, is there any suggested threshold for difference between the highest case count and highest control count? For example, if the highest case count is 25 and the highest control count is 15, then the difference is 10. If there is a threshold for the difference (like 8), then the TR expansion is probably pathogenic.

Best regards，
Stanley

> 
> 
> Hi Stanley. Thank you for the questions.
> 
>     1. That's right. The vast majority of controls have very low counts (zero) but a few controls have very high counts.
> 
>     2. That's right, long repeats were detected only in 13 samples. You could get the raw counts from the corresponding [multisample profile](https://github.com/Illumina/ExpansionHunterDenovo/blob/master/documentation/06_Merging_profiles.md). We will add an option to display sample names for all counts in the "counts" column in the future.
> 
>     3. Unfortunately not yet. However, long homozygous expansions will generate higher counts (of anchored in-repeat reads) compared to long heterozygous expansions.
> 
>     4. Could you please explain this question a bit more? I am not sure I understood it.
> 
> 
> I hope this helps! Please let me know if any of my answers are not clear.
> 
> Best wishes,
> Egor

**Comment by egor-dolzhenko** [comment]
Hello Stanley,

These are interesting questions!

In general, it is better to not make any conclusions about pathogenicity based on EHdn results alone. The aim of EHdn is just to find either (a) rare, outlier expansions or (b) more systematic differences between cases and controls. So EHdn produces candidates for further studies aimed at establishing pathogenicity.

For (1), you could say that this TR is a less likely pathogenic repeat expansion candidate compared to expansions that are completely absent from the control population (however the control population may have carriers of this expansion so it makes sense to not completely rule out such repeats).

For (2), we don't have a specific threshold, but it could be useful to rank the repeats based on the difference between the highest case count and the highest control count (keeping in mind that carriers might be present in controls).

For (3), yes EHdn can detect de novo mutations. If there is a long repeat in some samples that is not presented in the reference, EHdn will detect it.

I hope these answers are helpful. Please let me know if you have any other questions.

Best wishes,
Egor

**Comment by swlx08** [comment]
> 
> 
> Hello Stanley,
> 
> These are interesting questions!
> 
> In general, it is better to not make any conclusions about pathogenicity based on EHdn results alone. The aim of EHdn is just to find either (a) rare, outlier expansions or (b) more systematic differences between cases and controls. So EHdn produces candidates for further studies aimed at establishing pathogenicity.
> 
> For (1), you could say that this TR is a less likely pathogenic repeat expansion candidate compared to expansions that are completely absent from the control population (however the control population may have carriers of this expansion so it makes sense to not completely rule out such repeats).
> 
> For (2), we don't have a specific threshold, but it could be useful to rank the repeats based on the difference between the highest case count and the highest control count (keeping in mind that carriers might be present in controls).
> 
> For (3), yes EHdn can detect de novo mutations. If there is a long repeat in some samples that is not presented in the reference, EHdn will detect it.
> 
> I hope these answers are helpful. Please let me know if you have any other questions.
> 
> Best wishes,
> Egor

Dear Egor,

Thank you so much for your reply! I have four more questions.

(1) I calculated the difference between the highest case count and the highest control count, and ranked the TRs based on it:
![图片](https://user-images.githubusercontent.com/36035647/128452035-26790d4a-2733-4eb8-9ffe-7fb68bc778c6.png)

In the table above there are four TRs with zscore > 10 but with difference < 0. So could I exclude these TRs in next-step analysis because some controls have longer expansions than the cases for these TRs?

(2) The table below shows the counts for cases and all samples. We collected the trio samples, which means for those cases with high counts, their parents (controls) may also have high counts (as you mention that carriers might be present in controls). So if possible could EHdn add some options to consider trio information in the future?

![图片](https://user-images.githubusercontent.com/36035647/128490356-2794f8d2-f4e3-4099-b8f3-b87585cb8883.png)

（3） Would contraction of TRs be pathogenic?

(4) In the latest review (30 years of repeat expansion disorders: What have we learned and what are the remaining challenges?) the author mentioned:
"SCAs are a clinically and genetically heterogeneous group of autosomal-dominant disorders, characterized by gait imbalance as the result of the progressive loss of cerebellar neurons. SCA37 (MIM: 615945) was first mapped to 1p32 in a large Spanish family, and the interval was confirmed and further refined to 2.8 Mb in three Portuguese families. The systematic search for repeat expansions in this interval led to the identification of an intronic expansion composed of ATTTT repeats with an insertion of ATTTC motifs in DAB1 (MIM: 603448). Pathogenic expansions all contain the ATTTC insertion, ranging from 31 to 75 repeats, flanked by variable stretches of ATTTT repeats,
while larger pure ATTTT expansions (up to 400 repeats) are present in healthy individuals."

It seems that in some situations an insertion of certain motifs in some TRs would be more pathogenic than larger pure expansions. So would EHdn consider this effect in the future?

Best regards, 
Stanley

**Comment by egor-dolzhenko** [comment]
Dear Stanley,

Thanks for the additional questions. Here are my brief answers. Please let me know if I misunderstood any of the questions or didn't answer something completely.

1. Personally, I would not exclude these completely, maybe just assign these repeats a lower priority (just to account for the possibility that your controls might have some carriers of this expansion).
2. Absolutely! We will think of a good way to add trio support in the future versions of EHdn.
3. I believe there are some known pathogenic repeat contractions. Although the current version of EHdn is designed for detecting expansions, we could modify the program to search for contractions if there is enough interest in this feature.
4. EHdn can do this to some extent. If there is a long ATTTC expansion, EHdn would detect it as de novo expansion (which will have non-zero IRR count in the corresponding case and zero counts in controls). We will try to better support such repeats in the future versions of EHdn.
5. I may not be the best person to answer this question. But this seems like an interesting analysis direction to explore.
6. That's right. If there is a large expansion of a repeat in one of the cases and this repeat is absent (or short) in controls, you would get a large count in the case sample and zeros in controls.

Best wishes,
Egor

**Comment by swlx08** [comment]
> 
> 
> Dear Stanley,
> 
> Thanks for the additional questions. Here are my brief answers. Please let me know if I misunderstood any of the questions or didn't answer something completely.
> 
>     1. Personally, I would not exclude these completely, maybe just assign these repeats a lower priority (just to account for the possibility that your controls might have some carriers of this expansion).
> 
>     2. Absolutely! We will think of a good way to add trio support in the future versions of EHdn.
> 
>     3. I believe there are some known pathogenic repeat contractions. Although the current version of EHdn is designed for detecting expansions, we could modify the program to search for contractions if there is enough interest in this feature.
> 
>     4. EHdn can do this to some extent. If there is a long ATTTC expansion, EHdn would detect it as de novo expansion (which will have non-zero IRR count in the corresponding case and zero counts in controls). We will try to better support such repeats in the future versions of EHdn.
> 
>     5. I may not be the best person to answer this question. But this seems like an interesting analysis direction to explore.
> 
>     6. That's right. If there is a large expansion of a repeat in one of the cases and this repeat is absent (or short) in controls, you would get a large count in the case sample and zeros in controls.
> 
> 
> Best wishes,
> Egor

Dear Egor,

Thank you so much for your helpful and patient answers! Sorry I hope to ask for two more questions.

（1） I checked the multisample_profile.json file to get the raw count for every sample. As shown in the figure below, NT199 is a case, and NT200 is his/her mother. But the count here is the raw count, not the count normalized by the sequencing depth. So could you please tell me how can I get the normalized count for NT200?
![圖片](https://user-images.githubusercontent.com/36035647/129655789-3d2f3610-d1d2-4caf-b525-c4eeaecf66c3.png)

（2） I found some TR expansions which are suspicious for causing disease. Then how should I validate their potential pathogenicity? Southern bloting, RP-PCR or long reads sequencing could only confirm the existence of TR expansions, but not their pathogenicity.

Thanks again and best regards,
Stanley

**Comment by swlx08** [comment]
Dear Egor,

I am so sorry for asking so many questions. Could you please just tell me how can I get the the normalized counts for all samples with corresponding IDs?

**Comment by egor-dolzhenko** [comment]
Dear Stanley,

Apologies for the slow reply. You can use the following simple normalization formula `target_depth * count / sample_depth`.  For example, if you have a raw count of 17 that you want to normalize to 40x depth and the genome wide depth of the sample is, say, 35x, the corresponding normalized count is 40 * 17 / 35 = 19.43. The genome depth estimates are provided under "Parameters" field in the JSON file. It looks approximately like this:

```
    "Parameters": {
        "Depths": {
            "SAMPLE1": 38.56594881764087,
            "SAMPLE2": 37.77882984215736,
            "SAMPLE3": 42.70300807210033,
    ...
```
Also about your earlier question on validating potential pathogenicity of repeat expansions. I think this and other similar articles can be useful guides: https://www.nejm.org/doi/full/10.1056/NEJMoa1806627. A good initial step after the presence of an expansion was confirmed could be to establish that the expansion is appropriately rare (by showing that it is absent in an appropriate set of controls).

**Comment by swlx08** [comment]
> 
> 
> Dear Stanley,
> 
> Apologies for the slow reply. You can use the following simple normalization formula `target_depth * count / sample_depth`. For example, if you have a raw count of 17 that you want to normalize to 40x depth and the genome wide depth of the sample is, say, 35x, the corresponding normalized count is 40 * 17 / 35 = 19.43. The genome depth estimates are provided under "Parameters" field in the JSON file. It looks approximately like this:
> 
> ```
>     "Parameters": {
>         "Depths": {
>             "SAMPLE1": 38.56594881764087,
>             "SAMPLE2": 37.77882984215736,
>             "SAMPLE3": 42.70300807210033,
>     ...
> ```
> 
> Also about your earlier question on validating potential pathogenicity of repeat expansions. I think this and other similar articles can be useful guides: https://www.nejm.org/doi/full/10.1056/NEJMoa1806627. A good initial step after the presence of an expansion was confirmed could be to establish that the expansion is appropriately rare (by showing that it is absent in an appropriate set of controls).

Dear Egor, 

Thank you so much for your help. I really appreciate that.

Best regards,
Stanley
