### ISSUE TITLE
'Parameters' object has no attribute 'target_regions'

### ISSUE THREAD

**Issue by katherinesmith** [Illumina/ExpansionHunterDenovo#6]
Hi! I'm trying to run `casecontrol.py locus` with option `--target-regions targets.bed` and getting the following error:

```Traceback (most recent call last):
  File "/sw/ExpansionHunterDenovo-v0.8.0-linux_x86_64/scripts/casecontrol.py", line 166, in <module>
    main()
  File "/sw/ExpansionHunterDenovo-v0.8.0-linux_x86_64/scripts/casecontrol.py", line 162, in main
    args.run_workflow(args)
  File "/sw/ExpansionHunterDenovo-v0.8.0-linux_x86_64/scripts/casecontrol.py", line 137, in run_locus_workflow
    casecontrol.locusworkflow.run(params)
  File "/sw/ExpansionHunterDenovo-v0.8.0-linux_x86_64/scripts/casecontrol/locusworkflow.py", line 113, in run
    target_regions = load_target_regions(params.target_regions)
AttributeError: 'Parameters' object has no attribute 'target_regions'
```

After a quick look at the code I hypothesise that this might be fixed by changing
https://github.com/Illumina/ExpansionHunterDenovo/blob/6f2f77316d958455751c5a978253569d487dc6a3/scripts/casecontrol/locusworkflow.py#L113
to `target_regions = load_target_regions(params.target_region_path)`.?

Best wishes,

Katherine

**Comment by egor-dolzhenko** [comment]
Thank you for reporting the bug, Katherine! I just applied the change you suggested. Are you running released versions or are you using the master branch? If you are using releases, I will create a minor release with this change.

Best wishes,
Egor

**Comment by katherinesmith** [comment]
Thanks @egor-dolzhenko for the speedy reply. It would be great to have the change in the next minor release, but there is no huge hurry :)

**Comment by egor-dolzhenko** [comment]
@katherinesmith, I just made [the release](https://github.com/Illumina/ExpansionHunterDenovo/releases/tag/v0.8.7). Please let us know if you encounter any other problems or if there are any useful features we could add.

**Comment by katherinesmith** [comment]
Thanks very much, will do!
